"""Add user tier field for rate limiting

Revision ID: 10dbeca76f8c
Revises: add_tags_tables
Create Date: 2025-07-16 15:53:46.182349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10dbeca76f8c'
down_revision: Union[str, None] = 'add_tags_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_images_created_at_desc', table_name='images')
    op.drop_index('idx_images_description_trgm', table_name='images', postgresql_using='gin')
    op.drop_index('idx_images_file_type', table_name='images')
    op.drop_index('idx_images_is_nsfw', table_name='images')
    op.drop_index('idx_images_privacy_created', table_name='images')
    op.drop_index('idx_images_privacy_nsfw_created', table_name='images')
    op.drop_index('idx_images_search_gin', table_name='images', postgresql_using='gin')
    op.drop_index('idx_images_title_trgm', table_name='images', postgresql_using='gin')
    op.drop_index('idx_images_views', table_name='images')
    op.drop_index('idx_images_views_desc', table_name='images')
    op.add_column('users', sa.Column('tier', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tier')
    op.create_index('idx_images_views_desc', 'images', [sa.text('views DESC')], unique=False)
    op.create_index('idx_images_views', 'images', ['views'], unique=False)
    op.create_index('idx_images_title_trgm', 'images', ['title'], unique=False, postgresql_using='gin')
    op.create_index('idx_images_search_gin', 'images', [sa.text("to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('idx_images_privacy_nsfw_created', 'images', ['privacy', 'is_nsfw', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_images_privacy_created', 'images', ['privacy', 'created_at'], unique=False)
    op.create_index('idx_images_is_nsfw', 'images', ['is_nsfw'], unique=False)
    op.create_index('idx_images_file_type', 'images', ['file_type'], unique=False)
    op.create_index('idx_images_description_trgm', 'images', ['description'], unique=False, postgresql_using='gin')
    op.create_index('idx_images_created_at_desc', 'images', [sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###